// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article_service.proto

package article

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Article struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string     `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Comments             []*Comment `protobuf:"bytes,5,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Article) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Comment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ArticleId            string   `protobuf:"bytes,4,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{1}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Comment) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type CreateArticleRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleRequest) Reset()         { *m = CreateArticleRequest{} }
func (m *CreateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest) ProtoMessage()    {}
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{2}
}

func (m *CreateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest.Unmarshal(m, b)
}
func (m *CreateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest.Merge(m, src)
}
func (m *CreateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest.Size(m)
}
func (m *CreateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest proto.InternalMessageInfo

func (m *CreateArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateArticleRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type CreateArticleResponse struct {
	Article              *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleResponse) Reset()         { *m = CreateArticleResponse{} }
func (m *CreateArticleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateArticleResponse) ProtoMessage()    {}
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{3}
}

func (m *CreateArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleResponse.Unmarshal(m, b)
}
func (m *CreateArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleResponse.Marshal(b, m, deterministic)
}
func (m *CreateArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleResponse.Merge(m, src)
}
func (m *CreateArticleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateArticleResponse.Size(m)
}
func (m *CreateArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleResponse proto.InternalMessageInfo

func (m *CreateArticleResponse) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type GetArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleRequest) Reset()         { *m = GetArticleRequest{} }
func (m *GetArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleRequest) ProtoMessage()    {}
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{4}
}

func (m *GetArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleRequest.Unmarshal(m, b)
}
func (m *GetArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleRequest.Merge(m, src)
}
func (m *GetArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleRequest.Size(m)
}
func (m *GetArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleRequest proto.InternalMessageInfo

func (m *GetArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetArticleResponse struct {
	Article              *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleResponse) Reset()         { *m = GetArticleResponse{} }
func (m *GetArticleResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleResponse) ProtoMessage()    {}
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{5}
}

func (m *GetArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleResponse.Unmarshal(m, b)
}
func (m *GetArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleResponse.Merge(m, src)
}
func (m *GetArticleResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleResponse.Size(m)
}
func (m *GetArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleResponse proto.InternalMessageInfo

func (m *GetArticleResponse) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleRequest) Reset()         { *m = UpdateArticleRequest{} }
func (m *UpdateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleRequest) ProtoMessage()    {}
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{6}
}

func (m *UpdateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleRequest.Unmarshal(m, b)
}
func (m *UpdateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleRequest.Merge(m, src)
}
func (m *UpdateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleRequest.Size(m)
}
func (m *UpdateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleRequest proto.InternalMessageInfo

func (m *UpdateArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateArticleRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type UpdateArticleResponse struct {
	Article              *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleResponse) Reset()         { *m = UpdateArticleResponse{} }
func (m *UpdateArticleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleResponse) ProtoMessage()    {}
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{7}
}

func (m *UpdateArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleResponse.Unmarshal(m, b)
}
func (m *UpdateArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleResponse.Merge(m, src)
}
func (m *UpdateArticleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleResponse.Size(m)
}
func (m *UpdateArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleResponse proto.InternalMessageInfo

func (m *UpdateArticleResponse) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type AddCommentRequest struct {
	ArticleId            string   `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommentRequest) Reset()         { *m = AddCommentRequest{} }
func (m *AddCommentRequest) String() string { return proto.CompactTextString(m) }
func (*AddCommentRequest) ProtoMessage()    {}
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{8}
}

func (m *AddCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentRequest.Unmarshal(m, b)
}
func (m *AddCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentRequest.Marshal(b, m, deterministic)
}
func (m *AddCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentRequest.Merge(m, src)
}
func (m *AddCommentRequest) XXX_Size() int {
	return xxx_messageInfo_AddCommentRequest.Size(m)
}
func (m *AddCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentRequest proto.InternalMessageInfo

func (m *AddCommentRequest) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *AddCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AddCommentRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type AddCommentResponse struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommentResponse) Reset()         { *m = AddCommentResponse{} }
func (m *AddCommentResponse) String() string { return proto.CompactTextString(m) }
func (*AddCommentResponse) ProtoMessage()    {}
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f60f916b6c13b, []int{9}
}

func (m *AddCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommentResponse.Unmarshal(m, b)
}
func (m *AddCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommentResponse.Marshal(b, m, deterministic)
}
func (m *AddCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommentResponse.Merge(m, src)
}
func (m *AddCommentResponse) XXX_Size() int {
	return xxx_messageInfo_AddCommentResponse.Size(m)
}
func (m *AddCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommentResponse proto.InternalMessageInfo

func (m *AddCommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func init() {
	proto.RegisterType((*Article)(nil), "article.Article")
	proto.RegisterType((*Comment)(nil), "article.Comment")
	proto.RegisterType((*CreateArticleRequest)(nil), "article.CreateArticleRequest")
	proto.RegisterType((*CreateArticleResponse)(nil), "article.CreateArticleResponse")
	proto.RegisterType((*GetArticleRequest)(nil), "article.GetArticleRequest")
	proto.RegisterType((*GetArticleResponse)(nil), "article.GetArticleResponse")
	proto.RegisterType((*UpdateArticleRequest)(nil), "article.UpdateArticleRequest")
	proto.RegisterType((*UpdateArticleResponse)(nil), "article.UpdateArticleResponse")
	proto.RegisterType((*AddCommentRequest)(nil), "article.AddCommentRequest")
	proto.RegisterType((*AddCommentResponse)(nil), "article.AddCommentResponse")
}

func init() {
	proto.RegisterFile("article_service.proto", fileDescriptor_8e8f60f916b6c13b)
}

var fileDescriptor_8e8f60f916b6c13b = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x25, 0xf1, 0xf9, 0xa2, 0xf7, 0xa1, 0x3c, 0x07, 0x2d, 0x83, 0x62, 0x91, 0x74, 0x23, 0xa5,
	0x28, 0xd8, 0x1f, 0xd0, 0x8a, 0x14, 0x37, 0x2e, 0x2c, 0xdd, 0x74, 0x23, 0x69, 0xe6, 0x42, 0x07,
	0x34, 0x63, 0x93, 0xb1, 0x5f, 0xd2, 0xef, 0xe9, 0xb7, 0x95, 0x26, 0x33, 0xc9, 0x98, 0xc4, 0x42,
	0x85, 0xee, 0x32, 0xf7, 0x9e, 0xe4, 0x9c, 0x9c, 0x73, 0x12, 0xe8, 0x78, 0xa1, 0xe4, 0xfe, 0x16,
	0x37, 0x11, 0x86, 0x6f, 0xdc, 0xc7, 0xd1, 0x3e, 0x14, 0x52, 0x10, 0x47, 0x8d, 0xdd, 0x77, 0x0b,
	0x9c, 0x59, 0x72, 0x4d, 0x9a, 0x60, 0x73, 0x46, 0xad, 0x81, 0x35, 0xac, 0xaf, 0x6d, 0xce, 0x48,
	0x1b, 0xaa, 0x92, 0xcb, 0x2d, 0x52, 0x3b, 0x1e, 0x25, 0x07, 0x42, 0xc1, 0xf1, 0x45, 0x20, 0x31,
	0x90, 0xb4, 0x12, 0xcf, 0xf5, 0x91, 0xf4, 0xa0, 0xee, 0x1d, 0xe4, 0x8b, 0x08, 0x37, 0x9c, 0xd1,
	0x3f, 0xf1, 0xae, 0x96, 0x0c, 0x96, 0x8c, 0xdc, 0x40, 0xcd, 0x17, 0xbb, 0x1d, 0x06, 0x32, 0xa2,
	0xd5, 0x41, 0x65, 0xf8, 0x6f, 0xf2, 0x7f, 0xa4, 0x44, 0x8c, 0xe6, 0xc9, 0x62, 0x9d, 0x22, 0x5c,
	0x01, 0x8e, 0x1a, 0x16, 0x54, 0x19, 0xfc, 0xf6, 0x37, 0xfc, 0x95, 0x1c, 0x7f, 0x1f, 0x40, 0x5b,
	0x91, 0xaa, 0xab, 0xab, 0xc9, 0x92, 0xb9, 0x3e, 0xb4, 0xe7, 0x21, 0x7a, 0x12, 0x95, 0x19, 0x6b,
	0x7c, 0x3d, 0x60, 0x24, 0x33, 0x0f, 0xac, 0x13, 0x1e, 0xfc, 0x40, 0x83, 0x3b, 0x87, 0x4e, 0x8e,
	0x24, 0xda, 0x8b, 0x20, 0x42, 0x72, 0x0d, 0x3a, 0x90, 0x98, 0xc7, 0xf4, 0x46, 0x43, 0xd3, 0xc4,
	0xae, 0xa0, 0x75, 0x8f, 0x32, 0x27, 0x33, 0x67, 0x92, 0x3b, 0x05, 0x62, 0x82, 0xce, 0xa0, 0x89,
	0xa0, 0xfd, 0xb8, 0x67, 0x45, 0x43, 0x7e, 0xb3, 0x24, 0x5f, 0x06, 0xe5, 0x48, 0xcf, 0x50, 0xce,
	0xa1, 0x35, 0x63, 0x4c, 0x77, 0x4a, 0xc9, 0x3e, 0x8e, 0xdf, 0xca, 0xc5, 0x7f, 0x6e, 0xa0, 0x53,
	0x20, 0x26, 0x55, 0x26, 0x56, 0x15, 0xb9, 0x20, 0x56, 0x43, 0x35, 0x60, 0xf2, 0x61, 0x43, 0x53,
	0xbd, 0xc1, 0x43, 0xf2, 0x85, 0x92, 0x15, 0x34, 0x8e, 0x5a, 0x42, 0xfa, 0xd9, 0xed, 0x25, 0x15,
	0xed, 0x5e, 0x9e, 0x5a, 0x2b, 0x39, 0x0b, 0x80, 0xac, 0x0b, 0xa4, 0x9b, 0xa2, 0x0b, 0x2d, 0xea,
	0xf6, 0x4a, 0x77, 0xea, 0x31, 0x2b, 0x68, 0x1c, 0x65, 0x63, 0xc8, 0x2a, 0x2b, 0x8a, 0x21, 0xab,
	0x3c, 0xd2, 0x05, 0x40, 0xe6, 0x9d, 0x21, 0xab, 0x90, 0x9d, 0x21, 0xab, 0x68, 0xf6, 0x1d, 0x7d,
	0xba, 0xe0, 0x81, 0xc4, 0x30, 0xf0, 0xb6, 0xe3, 0xf8, 0xdf, 0x36, 0x56, 0xe0, 0xe7, 0xbf, 0xf1,
	0xf1, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x19, 0x1b, 0x24, 0x57, 0x03, 0x05, 0x00, 0x00,
}
